### ISSUE TITLE
SDK-KEY is mandatory when using ld-relay as proxy?

### ISSUE THREAD

**Issue by juniorb2ss** [launchdarkly/php-server-sdk#126]
I did some testing and realized that when using `ld-relay` as a proxy, `sdk-key` is not mandatory.

Can I use the library without configure `sdk-key` in the library when using with `ld-relay` as proxy?

If not, what are the reasons?

Thanks in advance for any help!

**Comment by eli-darkly** [comment]
Can you describe your test steps? The relay should always require an SDK key, mobile key, or client-side environment ID, depending on which endpoints you are accessing. That's true regardless of whether you're using PHP or another platform.

**Comment by juniorb2ss** [comment]
> Can you describe your test steps? The relay should always require an SDK key, mobile key, or client-side environment ID, depending on which endpoints you are accessing. This is because it can proxy multiple LaunchDarkly environments and has to be able to distinguish between them, and also just so that the relay does not become a completely unauthenticated entry point into your LD account. That's true regardless of whether you're using PHP or another platform.

Hello @eli-darkly, thanks for the reply.

I just pass `sdk-key` as null and `ld-relay` redis configuration and everything works normally. This is a reason I made myself this question.

**Comment by eli-darkly** [comment]
Oh I see, you're talking about not using the relay's REST endpoints at all, just getting the flags from the database. In that case, you're right that the SDK key is not used. And in fact, as you found, the PHP SDK will not give you an error if you pass an arbitrary value like `"x"`, or `""`, or even `null`.

In that case, I think what you're asking is whether we could make the whole _parameter_ optional in the method signature (as opposed to making its value optional, which it already is) - so you could call `new LDClient()` instead of `new LDClient(null)`. We could, but I'm unclear on the advantage of doing so. Either way, you are not being required to "configure sdk-key in the library".

**Comment by juniorb2ss** [comment]
> Oh I see, you're talking about not using the relay's REST endpoints at all, just getting the flags from the database. In that case, you're right that the SDK key is not used. And in fact, as you found, the PHP SDK will not give you an error if you pass an arbitrary value like `"x"`, or `""`, or even `null`.
> 
> In that case, I think what you're asking is whether we could make the whole _parameter_ optional in the method signature (as opposed to making its value optional, which it already is) - so you could call `new LDClient()` instead of `new LDClient(null)`. We could, but I'm unclear on the advantage of doing so. Either way, you are not being required to "configure sdk-key in the library".

Thanks for the clarification!

Yep, exactly that. I'm not using the endpoints from `ld-relay`, just redis database.

I just wondered why we have the `track` method, and how does this method work without `sdk-key`? Does it use `ld-relay` too?

I don't see reason to change `LDClient::__construct` signature, it's okay for me pass `sdk-key` as `null`

**Comment by eli-darkly** [comment]
Analytics events in general—whether they are created by `track`, or `identify`, or just evaluating a feature flag—are delivered to LaunchDarkly by one of two mechanisms (directly to LD, or to an endpoint of ld-relay), but both of them require a valid SDK key. So if you want to see _any_ event data on your dashboard from your PHP app, you do need the key.

**Comment by juniorb2ss** [comment]
> Analytics events in general—whether they are created by `track`, or `identify`, or just evaluating a feature flag—are delivered to LaunchDarkly by one of two mechanisms (directly to LD, or to an endpoint of ld-relay), but both of them require a valid SDK key. So if you want to see _any_ event data on your dashboard from your PHP app, you do need the key.

Oh, Thanks! So I will pass the correctly `sdk-key`.
