### ISSUE TITLE
Toggle Feature Flags for a user via the SDK

### ISSUE THREAD

**Issue by jacobsmith** [launchdarkly/php-server-sdk#131]
**Is your feature request related to a problem? Please describe.**
Our internal team uses LaunchDarkly to enable/disable portions of our application, specifically around billing. Because these billing steps are largely automated, I'd like to be able to have our internal administrative tool kick off changes to a user's subscription, including showing them a different payment page (say, moving from a mailed invoice to a credit card). To do this, I would add the user to a custom rule-set (matching on ID) since it's a case-by-case basis that customers may request certain features.

**Describe the solution you'd like**
Ideally, the PHP SDK would support the API method ( https://apidocs.launchdarkly.com/reference#update-flag-setting-for-user ) that would enable this.

**Describe alternatives you've considered**
I will probably have to manually create API requests instead of using the SDK.

**Additional context**

Thanks!

**Comment by bwoskow-ld** [comment]
Hi @jacobsmith,

Our SDKs (such as `php-server-sdk`) are intended to run within customers' applications to base your application behavior on flag state. The SDKs aren't meant to be holistic client libraries for LaunchDarkly's APIs.

Luckily for you, we also offer a set of client-libraries for that more general purpose -- including a [PHP client](https://github.com/launchdarkly/api-client-php). For your particular use case I believe you want to use [this API](https://github.com/launchdarkly/api-client-php/blob/master/LaunchDarklyApi/lib/Api/UserSettingsApi.php#L734).

Let me know if that answers your question!

Ben

**Comment by jacobsmith** [comment]
@bwoskow-ld Awesome, thank you so much! Yes, clearly I didn't realize that the server-sdk was different from the client-library. Thanks for pointing that out! 🎉
