### ISSUE TITLE
Composer 1.10 throws a deprecation notice (for 2.0) about class loading for NullEventProcessor

### ISSUE THREAD

**Issue by bfenton-smugmug** [launchdarkly/php-server-sdk#135]
**Is this a support request?**
No

**Describe the bug**

```
Deprecation Notice: Class LaunchDarkly\NullEventProcessor located in ./vendor/launchdarkly/server-sdk/src/LaunchDarkly/Impl/NullEventProcessor.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
```

**To reproduce**

* Install at least version 1.10 of composer
* Composer install the latest version of php-server-sdk
* If necessary, run `composer dump-autoload -o`, but the above should do it

**Expected behavior**
Expected to not have any notices

**Logs**
See above

**SDK version**
3.7.2

**Language version, developer tools**
PHP 7.4.5, CLI SAPI

**OS/platform**
OSX Catalina

**Additional context**

Should be fixed by https://github.com/launchdarkly/php-server-sdk/pull/134

**Comment by eli-darkly** [comment]
This is fixed in the 3.7.2 release. Thanks for the PR.
