### ISSUE TITLE
DynamoDbFeatureRequester prefix/namespace inconsistent with NodeJS equivalent prefix:namespace.

### ISSUE THREAD

**Issue by MrAdamCook** [launchdarkly/php-server-sdk#138]
When attempting to implement our LD Relay (Daemon Mode) on both NodeJS and PHP I noticed that the way prefixes and namespaces are coalesced are inconsistent.
In our DynamoDB for the LD Relay the namespace values are saved as so "website:test:features". This has resulted in the NodeJS implementation working as expected, but the PHP implementation can't find the same flags.

PHP SDK:
https://github.com/launchdarkly/php-server-sdk/blob/34462d5d47d5c4a1656afb68709faf6596ad852e/src/LaunchDarkly/Impl/Integrations/DynamoDbFeatureRequester.php#L29

NodeJS Server SDK:
`return prefix ? (prefix + ':' + baseNamespace) : baseNamespace;`
https://github.com/launchdarkly/node-server-sdk-dynamodb/blob/8ea55e68a057cfe4c7bb8de2aa5d9dd63b475f9d/dynamodb_feature_store.js#L174

**Comment by eli-darkly** [comment]
Thanks for catching this. I verified that all of the other SDKs have the same behavior as Node, so PHP is the only one that needs to be fixed. We should have a patch release out shortly.

**Comment by eli-darkly** [comment]
We've released version 3.7.3 with a fix for this.
