### ISSUE TITLE
Error when providing PHP Redis client to PHPRedisFeatureRequester

### ISSUE THREAD

**Issue by CameronHall** [launchdarkly/php-server-sdk#150]
**Describe the bug**
When providing an instance of the PHP-Redis client to PHPRedisFeatureRequester, it'll still try and set it up as if you were providing the array of options to configure it. 

This is because this condition fails:
https://github.com/launchdarkly/php-server-sdk/blob/6977789caf3162cc0b43f8e95b738cb8388018e9/src/LaunchDarkly/Impl/Integrations/PHPRedisFeatureRequester.php#L21
Similarly so does this one:
https://github.com/launchdarkly/php-server-sdk/blob/6977789caf3162cc0b43f8e95b738cb8388018e9/src/LaunchDarkly/Impl/Integrations/PHPRedisFeatureRequester.php#L50

This is because the conditions are checking against `Redis` under the `LaunchDarkly\Impl\Integrations`. So instead of checking if the provided client is an instance of Redis, it's checking if it's an instance of `LaunchDarkly\Impl\Integrations\Redis`. Prefixing `Redis` with a backslash will resolve the issue.

**To reproduce**
Provide a preconfigured PHP Redis client object like so:
```
LaunchDarkly\Integrations\PHPRedis::featureRequester(['phpredis_client' => $redis]);
```
Then try to fetch your feature flag list.

**Expected behaviour**
It should work 😄

**Logs**
N/A

**SDK version**
The version of this SDK that you are using.

**Language version, developer tools**
SDK Version 3.9

**OS/platform**
N/A

**Comment by eli-darkly** [comment]
Thanks for catching this. Looking now.

**Comment by CameronHall** [comment]
@eli-darkly any chance we can get a new patch release sometime soon?

**Comment by eli-darkly** [comment]
@CameronHall - Yes, sorry, it was held up last week by unrelated release deadlines.

**Comment by eli-darkly** [comment]
@CameronHall Version 3.9.1 is released with this fix.
