### ISSUE TITLE
0 Number value is not being save

### ISSUE THREAD

**Issue by Algeneralo** [launchdarkly/php-server-sdk#155]
**Describe the bug**
I have an integration with launchdarkly, but there is an issue when sending number values(only 0) , it's not being updated to user custom properties for some reason, but it works when I cast it to string

**To reproduce**
Send custom data with 0 value to the user

**Expected behavior**
Show the number value in the dashboard

**SDK version**
4.0

**Language version, developer tools**
PHP 8
Laravel 8

**OS/platform**
Ubuntu

**Comment by keelerm84** [comment]
Thank you for the report. This has been filed internally as ticket 138233. We will take a look and let you know!

**Comment by Algeneralo** [comment]
@keelerm84 after doing some tests also, the "false" boolean value also is not being saved

**Comment by keelerm84** [comment]
This has been fixed in version 4.1.0
