### ISSUE TITLE
Support for PSR/Log ^2.0

### ISSUE THREAD

**Issue by tommykent1210** [launchdarkly/php-server-sdk#157]
**Is your feature request related to a problem? Please describe.**
We are using the PHP SDK in our project, but it only supports PSR/Log ^1.0. We are currently using an internal fork of this repo using PSR/Log ^2.0 and see no problems with functionality.

**Describe the solution you'd like**
We'd like to see support for PSR/Log 2.0

**Describe alternatives you've considered**
Many modern Symfony based frameworks require 2.0 as a minimum, there are no alternatives.

**Comment by keelerm84** [comment]
Thank you for your feedback. We will let you know once we have a fix in place. 

Filed internally as sc-148686

**Comment by keelerm84** [comment]
This should be addressed in the new v4.2.0 release. Thanks again for your feedback!
