### ISSUE TITLE
TestData update generates error when updating a changed flag

### ISSUE THREAD

**Issue by aretenz** [launchdarkly/php-server-sdk#160]
According to the [docs](https://launchdarkly.github.io/php-server-sdk/classes/LaunchDarkly-Integrations-TestData.html#method_update), TestData update can be used more than once on the same flag if its definition has been changed. Specifically this paragraph:

`Any subsequent changes to this FlagBuilder instance do not affect the test data, unless you call update(FlagBuilder) again.`

However when it is called again on the same flag, an error is generated:

`Error: Cannot use object of type LaunchDarkly\Impl\Model\FeatureFlag as array`

I believe that is caused by line 133 in [TestData.php](https://github.com/launchdarkly/php-server-sdk/blob/main/src/LaunchDarkly/Integrations/TestData.php):

`           $oldVersion = $oldFlag['version'];`

The effect is that TestData does not update itself with the changed flag and still operates with the previous definition

If that line is changed as follows then the error no longer occurs:

`           $oldVersion = $oldFlag->getVersion();`

To test I used a simplified variation of testCanSetAndGetFeatureFlag in [TestDataTest.php](https://github.com/launchdarkly/php-server-sdk/blob/main/tests/Integrations/TestDataTest.php) that proceeds to change the flag definition and then update it again. 

At this stage I would need to install multiple versions of php for thorough testing. I have only tested it while running php 8.1.

The work around is:
- when updating a flag for a second time on the same TestData instance 
- then create a new TestData and LDClient and update on the new TestData.

**Comment by keelerm84** [comment]
Thank you for reporting this issue! Your fix seems reasonable to me.

> At this stage I would need to install multiple versions of php for thorough testing. I have only tested it while running php 8.1.

You should be able to verify the fix fairly easily via docker if you don't want to bother installing multiple versions of PHP. Something like `docker run --network=host --rm -it -v $(pwd):/home/circleci/project cimg/php:7.3 bash` will drop you into a container with the right version of PHP.

Alternatively, as long as you provide a good unit test, you can let our circleci test exercise the code in the various supported versions.

Or finally, we are happy to make the changes as well if you'd prefer. Your choice!

**Comment by aretenz** [comment]
I made a pr - unit-tested on 7.3, 7.4, 8.0, 8.1 using docker container

**Comment by keelerm84** [comment]
Your fix was released in version 4.2.2
