### ISSUE TITLE
Include monolog/monolog:^3.0 as dependency

### ISSUE THREAD

**Issue by juniorb2ss** [launchdarkly/php-server-sdk#163]
**Is your feature request related to a problem? Please describe.**
Is there a reason to not include `monolog/monolog:^3.0` in the required packages? The new version of this library may contain features that are necessary for the project, so if it is necessary to use the SDK in these projects, we would have to downgrade the package, causing a dependency hell.

The only block I see is referring to the PHP version because the package determines a minimum version of `8.1`. It might also be a good idea to release a version that uses new features from PHP 8.1.

**Describe the solution you'd like**
include `monolog/monolog:^3.0`

Any consideration?

**Comment by keelerm84** [comment]
It looks like we should be able to support this. I'll take a closer look today and keep you posted.

Filed internally as `sc-167767`.

**Comment by juniorb2ss** [comment]
Thank you, @keelerm84 !

**Comment by keelerm84** [comment]
Support for monolog 3.x has been added in `4.2.3`. 

As for removing monolog entirely, we will take it under consideration. We can't remove it without affecting SDK behavior, so it will have to wait until a subsequent release. Thank you for your input!
