### ISSUE TITLE
Curl events publisher causes FPM memory leak

### ISSUE THREAD

**Issue by mkopentag** [launchdarkly/php-server-sdk#166]
**Describe the bug**
After we have installed LD SDK we noticed a lot of such error in our logs.
**ALERT: oops, unknown child (43243) exited with code 0.** 

Also memory consumption started to increase gradually. And after some time FPM out of memory and unable to span new child processes.

Probably it's caused by [incorrect handling](https://bugs.php.net/bug.php?id=71989) of created child processes [inside curl events publisher](https://github.com/launchdarkly/php-server-sdk/blob/main/src/LaunchDarkly/Impl/Integrations/CurlEventPublisher.php#L110).

**To reproduce**
Just install the SDK and run a lot of requests to FPM with curl event publisher running [makeCurlRequest](https://github.com/launchdarkly/php-server-sdk/blob/main/src/LaunchDarkly/Impl/Integrations/CurlEventPublisher.php#L108) 

**Expected behavior**
No alerts and no memory leaks inside FPM

**Logs**
ALERT: oops, unknown child (43243) exited with code 0.

**SDK version**
launchdarkly/server-sdk 4.2.3

**Language version, developer tools**
PHP 8.1

**OS/platform**
Container-Optimized OS

**Comment by keelerm84** [comment]
Acknowledging here that we have seen this issue. I understand you are already in direct contact with support, so further communication will continue there.

Final resolution will be posted back to this issue. Thanks!

**Comment by intel352** [comment]
@keelerm84 Any resolution?

**Comment by keelerm84** [comment]
Thank you for the prompt @intel352 

Regarding the memory leak, I have not been able to reproduce that in my testing. I can trigger the error in the logs and I have witnessed where the memory can be held onto until the child process exits. However, in my testing, that memory is always freed so no leak seems evident.

As the original report shows, we are forking a child process to publish events. This is to ensure publication is asynchronous and doesn't block page load times. However, if your PHP script then finishes before event publication can complete, this warning will occur.

A couple of potential options for you:

- If the additional load times are acceptable, I would recommend switching to Guzzle for event publication. This method is synchronous, so your script processing will be blocked. Details can be found in the [PHP docs](https://launchdarkly.github.io/php-server-sdk/classes/LaunchDarkly-Integrations-Guzzle.html#method_eventPublisher).
- Depending on the execution flow of your application, manually triggering a `flush` on the LDClient as soon as all evaluation has been completed might lessen the frequency of the message. NOTE: This doesn't fix any problem, it just provides the event publication process more time to complete before the main script does.
- If you are not relying on events, you can disable them. I would recommend against this as events provide a lot of additional value in LaunchDarkly, but I did want to at least mention it.
