### ISSUE TITLE
Eliminate noisy log message

### ISSUE THREAD

**Issue by benharold** [launchdarkly/php-server-sdk#194]
**Is your feature request related to a problem? Please describe.**
Logs are full of the message:
```
GuzzleFeatureRequester is not using an HTTP cache because Kevinrob\GuzzleCache\CacheMiddleware was not installed
```

**Describe the solution you'd like**
Logs without the message:
```
GuzzleFeatureRequester is not using an HTTP cache because Kevinrob\GuzzleCache\CacheMiddleware was not installed
```

**Describe alternatives you've considered**
Installing the `Kevinrob\GuzzleCache\CacheMiddleware` library would eliminate the noise, but an optional library should not be required to eliminate log noise.

**Additional context**
None

**Comment by keelerm84** [comment]
Fixed in v5.2.1 and v6.0.2
