### ISSUE TITLE
utf8_encode is deprecated in PHP 8.2

### ISSUE THREAD

**Issue by malsatin** [launchdarkly/php-server-sdk#199]
**Is this a support request?**
No

**Describe the bug**
Functions `utf8_encode` and `utf8_decode` were [deprecated](https://www.php.net/releases/8.2/en.php#deprecations_and_bc_breaks) in PHP 8.2.
This SDK uses `utf8_encode` in one of it's functions - https://github.com/launchdarkly/php-server-sdk/blob/2a35991eb84d8968d45e307257f9760d0e1932b9/src/LaunchDarkly/Impl/Integrations/CurlEventPublisher.php#L132 which may produce deprecation warnings.

I suggest replacing `iconv("UTF-8", "UTF-16LE", utf8_encode($args))` with `mb_convert_encoding($args, 'UTF-16LE', 'ISO-8859-1')`

**To reproduce**
Make sure, that `error_reporting` is set to `E_ALL` in php.ini and call `CurlEventPublisher::publish()` function

**Expected behavior**
No warnings and exceptions are produced

**Logs**
You will get exception `Function utf8_encode() is deprecated` depending on your php configuration and logs behavior

**SDK version**
[v6.0.2](https://github.com/launchdarkly/php-server-sdk/releases/tag/6.0.2)

**Language version, developer tools**
PHP 8.3

**OS/platform**
Any

**Additional context**
This is preventing ticket, we don't use events sending and are not affected by that deprecation

**Comment by keelerm84** [comment]
I have merged a fix for this. It will go out in the next release (probably v6.1). Thank you so much for letting us know about this!
